// export const LMA11 = [
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "svg": "<svg width=\"152\" height=\"157\" viewBox=\"0 0 152 157\" xmlns=\"http://www.w3.org/2000/svg\">\r\n  <circle cx=\"75.1\" cy=\"75.1\" r=\"74.95\" stroke=\"#000000\" stroke-width=\"1.29\" fill=\"none\" />\r\n  <line x1=\"75.1\" y1=\"75.1\" x2=\"128.26\" y2=\"22.08\" stroke=\"#000000\" stroke-width=\"1.29\" stroke-linecap=\"round\" />\r\n  <circle cx=\"75.1\" cy=\"75.1\" r=\"2.25\" fill=\"#000000\" stroke=\"#000000\" stroke-width=\"0.3\" />\r\n  <g font-family=\"STIX Two Text, serif\" font-style=\"italic\" font-size=\"18\" fill=\"#000000\">\r\n    <text x=\"55.94\" y=\"81.56\">O</text>\r\n    <text x=\"128.02\" y=\"17.44\">A</text>\r\n  </g>\r\n</svg>",
//         "year": "24_10",
//         "num": "1",
//         "optionC": "Chord",
//         "description": "The circle below has centre \\(O\\).\n\\(A\\) is a point on the circumference of the circle.\nWhat name is given to the line that joins \\(O\\) and \\(A\\)?\n[[svg]]",
//         "topic": "geometry",
//         "optionD": "Arc",
//         "optionA": "Radius",
//         "optionB": "Diameter",
//         "qid": "LMA11_01_24_10_01"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "svg": "",
//         "year": "24_10",
//         "num": "2",
//         "optionC": "\\(210\\)",
//         "optionD": "\\(2940\\)",
//         "topic": "HCF",
//         "description": "What is the highest common factor of \\(42\\) and \\(70\\)?",
//         "optionA": "\\(7\\)",
//         "optionB": "\\(14\\)",
//         "qid": "LMA11_01_24_10_02"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "24_10",
//         "svg": "",
//         "num": "3",
//         "optionC": "\\(3\\)",
//         "description": "What is the order of rotational symmetry of a rectangle?",
//         "topic": "symmetry",
//         "optionD": "\\(4\\)",
//         "optionA": "\\(1\\)",
//         "optionB": "\\(2\\)",
//         "qid": "LMA11_01_24_10_03"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "svg": "<svg width=\"304\" height=\"147\" viewBox=\"0 0 304 147\" xmlns=\"http://www.w3.org/2000/svg\">\r\n  <line x1=\"0.14\" y1=\"84.23\" x2=\"303.47\" y2=\"84.23\" stroke=\"#000000\" stroke-width=\"1.29\" />\r\n  <line x1=\"33.05\" y1=\"146.78\" x2=\"117.39\" y2=\"0.7\" stroke=\"#000000\" stroke-width=\"1.29\" />\r\n  <path d=\"M 43.47 84.51 A 23.06 23.06 0 0 1 82.28 62.35\" fill=\"none\" stroke=\"#000000\" stroke-width=\"1.29\" />\r\n  <path d=\"M 93.99 29.16 L 104.01 23.82 L 104.41 35.17\" fill=\"none\" stroke=\"#000000\" stroke-width=\"1.29\" />\r\n  <line x1=\"186.89\" y1=\"146.78\" x2=\"271.23\" y2=\"0.7\" stroke=\"#000000\" stroke-width=\"1.29\" />\r\n  <path d=\"M 197.02 84.51 A 23.06 23.06 0 0 1 235.83 62.35\" fill=\"none\" stroke=\"#000000\" stroke-width=\"1.29\" />\r\n  <path d=\"M 247.65 29.16 L 257.67 23.82 L 258.07 35.17\" fill=\"none\" stroke=\"#000000\" stroke-width=\"1.29\" />\r\n  <g font-family=\"STIX Two Text, serif\" font-style=\"italic\" font-weight=\"400\" font-size=\"18\" fill=\"#000000\">\r\n    <text x=\"57.87\" y=\"80.16\">a</text>\r\n    <text x=\"213.58\" y=\"80.16\">b</text>\r\n  </g>\r\n</svg>",
//         "year": "24_10",
//         "num": "4",
//         "optionC": "Opposite angles",
//         "description": "Which phrase correctly describes the angles \\(a\\) and \\(b\\)?\n[[svg]]",
//         "optionD": "Alternate angles",
//         "topic": "",
//         "optionA": "Corresponding angles",
//         "optionB": "Co-interior angles",
//         "qid": "LMA11_01_24_10_04"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "year": "24_10",
//         "svg": "",
//         "num": "5",
//         "optionC": "\\(22y + 19\\)",
//         "description": "Simplify.\n\\[14y+8(3y+4)+15-3y\\]",
//         "optionD": "\\(22y + 27\\)",
//         "topic": "",
//         "optionA": "\\(35y + 47\\)",
//         "optionB": "\\(35y + 19\\)",
//         "qid": "LMA11_01_24_10_05"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "24_10",
//         "num": "6",
//         "optionC": "\\(4.087\\)",
//         "description": "What is \\(4.08657\\) rounded to 3 significant figures?",
//         "topic": "",
//         "optionD": "\\(4.09\\)",
//         "optionA": "\\(4.08\\)",
//         "optionB": "\\(4.086\\)",
//         "qid": "LMA11_01_24_10_06"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "24_10",
//         "num": "7",
//         "optionC": "\\(200\\) ml",
//         "description": "Amaan followed these instructions on a bottle of cordial.\n\"Mix two parts cordial with five parts water.\"\nHe used \\(280\\) ml of water.\nHow much cordial did Amaan use?",
//         "topic": "",
//         "optionD": "\\(700\\) ml",
//         "optionA": "\\(80\\) ml",
//         "optionB": "\\(112\\) ml",
//         "qid": "LMA11_01_24_10_07"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "svg": "",
//         "year": "24_10",
//         "num": "8",
//         "optionC": "\\(0.22\\)",
//         "optionD": "\\(0.283\\)",
//         "topic": "",
//         "description": "Work out \\[\\dfrac{\\dfrac{3}{4}-0.3^{2}\\times6}{8+4\\times\\sqrt{2.25}}\\]\nGive your answer to 3 decimal places.",
//         "optionA": "\\(0.012\\)",
//         "optionB": "\\(0.015\\)",
//         "qid": "LMA11_01_24_10_08"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_10",
//         "svg": "",
//         "num": "9",
//         "optionC": "\\(5\\dfrac{9}{40}\\)",
//         "optionD": "\\(6\\dfrac{9}{40}\\)",
//         "topic": "",
//         "description": "Work out \\[3\\dfrac{5}{8}+2\\dfrac{3}{5}\\]",
//         "optionA": "\\(1\\dfrac{1}{40}\\)",
//         "optionB": "\\(5\\dfrac{8}{13}\\)",
//         "qid": "LMA11_01_24_10_09"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "24_10",
//         "num": "10",
//         "optionC": "\\(7.07\\)",
//         "description": "If \\(E=400\\) and \\(m=8\\), find the value of \\(c\\) to 2 decimal places when \\(E=mc^{2}\\)",
//         "optionD": "\\(56.57\\)",
//         "topic": "",
//         "optionA": "\\(2.5\\)",
//         "optionB": "\\(6.25\\)",
//         "qid": "LMA11_01_24_10_10"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_10",
//         "svg": "",
//         "num": "11",
//         "optionC": "\\(0.5\\)",
//         "topic": "",
//         "optionD": "\\(0.6\\)",
//         "description": "Rafael plays a game of chess and then plays a game of backgammon.\nThe probability that he wins at chess and the probability that he wins at backgammon are independent.\nThe probability that he wins the game of chess is \\(0.3\\).\nThe probability that he wins the game of backgammon is \\(0.2\\).\nWhat is the probability that he wins both games?",
//         "optionA": "\\(0.05\\)",
//         "optionB": "\\(0.06\\)",
//         "qid": "LMA11_01_24_10_11"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_10",
//         "svg": "<svg viewBox=\"-75 0 775 700\" xmlns=\"http://www.w3.org/2000/svg\">\r\n  <defs>\r\n    <pattern id=\"grid\" width=\"70\" height=\"70\" patternUnits=\"userSpaceOnUse\" x=\"150\" y=\"20\">\r\n      <path d=\"M 14 0 v 70 M 28 0 v 70 M 42 0 v 70 M 56 0 v 70 M 0 14 h 70 M 0 28 h 70 M 0 42 h 70 M 0 56 h 70\" stroke=\"#dcdcdc\" stroke-width=\"1.5\" fill=\"none\"/>\r\n      <rect width=\"70\" height=\"70\" fill=\"none\" stroke=\"#a9a9a9\" stroke-width=\"2\" />\r\n    </pattern>\r\n    <g id=\"cross\" stroke=\"black\" stroke-width=\"2\" stroke-linecap=\"round\">\r\n      <line x1=\"-5\" y1=\"-5\" x2=\"5\" y2=\"5\" />\r\n      <line x1=\"-5\" y1=\"5\" x2=\"5\" y2=\"-5\" />\r\n    </g>\r\n  </defs>\r\n  <rect x=\"150\" y=\"20\" width=\"490\" height=\"560\" fill=\"url(#grid)\" />\r\n  <polyline points=\"150,20 150,580 640,580\" fill=\"none\" stroke=\"black\" stroke-width=\"4\" stroke-linecap=\"square\"/>\r\n  <g font-family=\"STIX Two Text\" font-size=\"18\" text-anchor=\"end\" fill=\"black\">\r\n    <text x=\"135\" y=\"25\">40</text>\r\n    <text x=\"135\" y=\"95\">35</text>\r\n    <text x=\"135\" y=\"165\">30</text>\r\n    <text x=\"135\" y=\"235\">25</text>\r\n    <text x=\"135\" y=\"305\">20</text>\r\n    <text x=\"135\" y=\"375\">15</text>\r\n    <text x=\"135\" y=\"445\">10</text>\r\n    <text x=\"135\" y=\"515\">5</text>\r\n    <text x=\"135\" y=\"585\">0</text>\r\n  </g>\r\n  <g font-family=\"STIX Two Text\" font-size=\"18\" text-anchor=\"middle\" fill=\"black\">\r\n    <text x=\"150\" y=\"615\">0</text>\r\n    <text x=\"220\" y=\"615\">5</text>\r\n    <text x=\"290\" y=\"615\">10</text>\r\n    <text x=\"360\" y=\"615\">15</text>\r\n    <text x=\"430\" y=\"615\">20</text>\r\n    <text x=\"500\" y=\"615\">25</text>\r\n    <text x=\"570\" y=\"615\">30</text>\r\n    <text x=\"640\" y=\"615\">35</text>\r\n  </g>\r\n  <g font-family=\"STIX Two Text\" font-size=\"20\" fill=\"black\">\r\n    <text x=\"5\" y=\"285\" text-anchor=\"middle\">Time spent playing</text>\r\n    <text x=\"5\" y=\"315\" text-anchor=\"middle\">Game B (minutes)</text>\r\n    <text x=\"395\" y=\"650\" text-anchor=\"middle\">Time spent playing Game A (minutes)</text>\r\n  </g>\r\n  <use href=\"#cross\" x=\"178\" y=\"230\" /> <use href=\"#cross\" x=\"248\" y=\"132\" /> <use href=\"#cross\" x=\"318\" y=\"244\" /> <use href=\"#cross\" x=\"332\" y=\"314\" /> <use href=\"#cross\" x=\"346\" y=\"272\" /> <use href=\"#cross\" x=\"402\" y=\"328\" /> <use href=\"#cross\" x=\"444\" y=\"370\" /> <use href=\"#cross\" x=\"486\" y=\"384\" /> <use href=\"#cross\" x=\"500\" y=\"286\" /> <use href=\"#cross\" x=\"570\" y=\"426\" /> <use href=\"#cross\" x=\"598\" y=\"468\" /> </svg>\r",
//         "num": "12",
//         "optionC": "\\(16\\) minutes",
//         "topic": "",
//         "optionD": "\\(21\\) minutes",
//         "description": "The scatter graph shows the time some students spent playing each of two different games.\n[[svg]]\nAnother student played Game B for \\(25\\) minutes.\nHow long would you expect this student to have spent playing Game A?",
//         "optionA": "\\(2\\) minutes",
//         "optionB": "\\(9\\) minutes",
//         "qid": "LMA11_01_24_10_12"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "svg": "",
//         "year": "24_10",
//         "num": "13",
//         "optionC": "Only Shunlong is correct",
//         "optionD": "Neither are correct",
//         "topic": "",
//         "description": "Qi and Shunlong are both trying to solve the equation \\[x^{2}-19=45\\]\nQi said \"\\(x=8\\) is a solution.\"\nShunlong said \"\\(x=-8\\) is a solution.\" Which one of these statements is correct?",
//         "optionA": "Both are correct",
//         "optionB": "Only Qi is correct",
//         "qid": "LMA11_01_24_10_13"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "year": "24_10",
//         "svg": "<svg width=\"550\" height=\"110\" viewBox=\"0 0 550 110\" xmlns=\"http://www.w3.org/2000/svg\">\r\n  <defs>\r\n    <marker id=\"arrow\" viewBox=\"0 0 10 10\" refX=\"6\" refY=\"5\" markerWidth=\"8\" markerHeight=\"8\" orient=\"auto-start-reverse\">\r\n      <path d=\"M 0 1.5 L 7 5 L 0 8.5 z\" fill=\"#1a1a1a\" />\r\n    </marker>\r\n    <line id=\"tick\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"12\" stroke=\"#1a1a1a\" stroke-width=\"1.2\" />\r\n  </defs>\r\n  <line x1=\"15\" y1=\"65\" x2=\"525\" y2=\"65\" stroke=\"#1a1a1a\" stroke-width=\"1.2\" />\r\n  <use href=\"#tick\" x=\"25\" y=\"65\" />   <use href=\"#tick\" x=\"70\" y=\"65\" />   <use href=\"#tick\" x=\"115\" y=\"65\" />  <use href=\"#tick\" x=\"160\" y=\"65\" />  <use href=\"#tick\" x=\"205\" y=\"65\" />  <use href=\"#tick\" x=\"250\" y=\"65\" />  <use href=\"#tick\" x=\"295\" y=\"65\" />  <use href=\"#tick\" x=\"340\" y=\"65\" />  <use href=\"#tick\" x=\"385\" y=\"65\" />  <use href=\"#tick\" x=\"430\" y=\"65\" />  <use href=\"#tick\" x=\"475\" y=\"65\" />  <g font-family=\"STIX Two Text, serif\" font-size=\"18\" text-anchor=\"middle\" fill=\"#1a1a1a\">\r\n    <text x=\"25\" y=\"98\">–5</text>\r\n    <text x=\"70\" y=\"98\">–4</text>\r\n    <text x=\"115\" y=\"98\">–3</text>\r\n    <text x=\"160\" y=\"98\">–2</text>\r\n    <text x=\"205\" y=\"98\">–1</text>\r\n    <text x=\"250\" y=\"98\">0</text>\r\n    <text x=\"295\" y=\"98\">1</text>\r\n    <text x=\"340\" y=\"98\">2</text>\r\n    <text x=\"385\" y=\"98\">3</text>\r\n    <text x=\"430\" y=\"98\">4</text>\r\n    <text x=\"475\" y=\"98\">5</text>\r\n    <text x=\"535\" y=\"69\" font-style=\"italic\" text-anchor=\"start\">x</text>\r\n  </g>\r\n  <line x1=\"115\" y1=\"32\" x2=\"525\" y2=\"32\" stroke=\"#1a1a1a\" stroke-width=\"2.2\" marker-end=\"url(#arrow)\" />\r\n  <circle cx=\"115\" cy=\"32\" r=\"5.5\" fill=\"#1a1a1a\" />\r\n</svg>",
//         "num": "14",
//         "optionC": "\\(x>-3\\)",
//         "description": "Which inequality is illustrated on the number line below?\n[[svg]]",
//         "topic": "",
//         "optionD": "\\(x\\ge-3\\)",
//         "optionA": "\\(x<-3\\)",
//         "optionB": "\\(x\\le-3\\)",
//         "qid": "LMA11_01_24_10_14"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "year": "24_10",
//         "svg": "",
//         "num": "15",
//         "optionC": "\\((x+6)^{2}\\)",
//         "description": "Factorise \\[x^{2}-12x+36\\]",
//         "optionD": "\\((x-6)^{2}\\)",
//         "topic": "",
//         "optionA": "\\((x+6)(x-6)\\)",
//         "optionB": "\\((x-6)(x+6)\\)",
//         "qid": "LMA11_01_24_10_15"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_05",
//         "svg": "",
//         "num": "1",
//         "optionC": "\\(\\dfrac{4}{19}\\)",
//         "topic": "",
//         "optionD": "\\(\\dfrac{4}{23}\\)",
//         "description": "A box contains only green pencils, red pencils and blue pencils.\nThere are \\(12\\) green pencils, \\(7\\) red pencils and \\(4\\) blue pencils.\nOne of the pencils is taken out of the box at random.\nWhat is the probability that the pencil taken out of the box is blue?",
//         "optionA": "\\(\\dfrac{4}{7}\\)",
//         "optionB": "\\(\\dfrac{4}{12}\\)",
//         "qid": "LMA11_01_24_05_01"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_05",
//         "svg": "",
//         "num": "2",
//         "optionC": "\\(244^{\\circ}\\)",
//         "topic": "",
//         "optionD": "\\(344^{\\circ}\\)",
//         "description": "Which of these is an obtuse angle?",
//         "optionA": "\\(44^{\\circ}\\)",
//         "optionB": "\\(144^{\\circ}\\)",
//         "qid": "LMA11_01_24_05_02"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "24_05",
//         "num": "3",
//         "optionC": "\\(31p+14q\\)",
//         "description": "Simplify \\[23p+9q-8p+5q\\]",
//         "optionD": "\\(31p+4q\\)",
//         "topic": "",
//         "optionA": "\\(15p+4q\\)",
//         "optionB": "\\(15p+14q\\)",
//         "qid": "LMA11_01_24_05_03"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "year": "24_05",
//         "svg": "",
//         "num": "4",
//         "optionC": "No correlation",
//         "description": "What type of correlation does this scatter graph show?\n[[scatter graph]]",
//         "topic": "",
//         "optionD": "Positive correlation",
//         "optionA": "Inconsistent correlation",
//         "optionB": "Negative correlation",
//         "qid": "LMA11_01_24_05_04"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "svg": "",
//         "year": "24_05",
//         "num": "5",
//         "optionC": "\\(7\\)",
//         "optionD": "\\(10\\)",
//         "topic": "",
//         "description": "The incomplete two-way table shows the favourite language and favourite science of each pupil in a class.\n[[table]]\nHow many pupils said Spanish is their favourite language and Physics their favourite science?",
//         "optionA": "\\(3\\)",
//         "optionB": "\\(4\\)",
//         "qid": "LMA11_01_24_05_05"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_05",
//         "svg": "",
//         "num": "6",
//         "optionC": "Sector",
//         "topic": "",
//         "optionD": "Segment",
//         "description": "Which word describes the area between a chord and an arc that joins each end of the chord in a circle?",
//         "optionA": "Circumference",
//         "optionB": "Diameter",
//         "qid": "LMA11_01_24_05_06"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "24_05",
//         "num": "7",
//         "optionC": "\\(790.0\\)",
//         "description": "Round \\(789.987\\) to one decimal place.",
//         "optionD": "\\(800\\)",
//         "topic": "",
//         "optionA": "\\(700\\)",
//         "optionB": "\\(789.9\\)",
//         "qid": "LMA11_01_24_05_07"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "year": "24_05",
//         "svg": "",
//         "num": "8",
//         "optionC": "\\((-5, 1)\\)",
//         "description": "Three points are plotted at the coordinates \\((-2, -1)\\), \\((0, 4)\\) and \\((3, 2)\\)\nAnother point is plotted so that all four can be joined to form a parallelogram.\nWhich of these could be the coordinates of the fourth point?\n[[graph]]",
//         "topic": "",
//         "optionD": "\\((2, -5)\\)",
//         "optionA": "\\((1, -1)\\)",
//         "optionB": "\\((-1, -5)\\)",
//         "qid": "LMA11_01_24_05_08"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "svg": "",
//         "year": "24_05",
//         "num": "9",
//         "optionC": "\\(7^{12}\\)",
//         "optionD": "\\(7^{32}\\)",
//         "topic": "",
//         "description": "Which single power of \\(7\\) is equal to \\((7^{8})^{4}\\)?",
//         "optionA": "\\(7^{2}\\)",
//         "optionB": "\\(7^{4}\\)",
//         "qid": "LMA11_01_24_05_09"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "svg": "",
//         "year": "24_05",
//         "num": "10",
//         "optionC": "\\(672\\)",
//         "topic": "",
//         "optionD": "\\(1248\\)",
//         "description": "Calculate \\[5^{3}-\\sqrt{1369}+8\\times(9+12\\div3)\\]",
//         "optionA": "\\(144\\)",
//         "optionB": "\\(192\\)",
//         "qid": "LMA11_01_24_05_10"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "year": "24_05",
//         "svg": "",
//         "num": "11",
//         "optionC": "\\(45\\)",
//         "description": "The scatter graph shows the marks some students scored on two examination papers.\n[[scattered graph]]\nAnother student scored \\(35\\) marks on Paper 1 but missed Paper 2.\nUse the scatter graph to estimate the marks this student would have scored on Paper 2.",
//         "optionD": "\\(60\\)",
//         "topic": "",
//         "optionA": "\\(15\\)",
//         "optionB": "\\(25\\)",
//         "qid": "LMA11_01_24_05_11"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_05",
//         "svg": "",
//         "num": "12",
//         "optionC": "\\(0.6\\)",
//         "topic": "",
//         "optionD": "\\(0.9\\)",
//         "description": "Find the value of \\[\\dfrac{t^{2}-\\sqrt{u+3s}}{2st}\\] when \\(s=-2\\), \\(t=5\\) and \\(u=11\\).\nGive your answer to 1 decimal place.",
//         "optionA": "\\(-0.9\\)",
//         "optionB": "\\(-0.6\\)",
//         "qid": "LMA11_01_24_05_12"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "year": "24_05",
//         "svg": "",
//         "num": "13",
//         "optionC": "\\(\\dfrac{678}{999}\\)",
//         "optionD": "\\(\\dfrac{678}{1000}\\)",
//         "topic": "",
//         "description": "What is \\(0.6\\dot{7}\\dot{8}\\) written as a fraction?",
//         "optionA": "\\(\\dfrac{611}{900}\\)",
//         "optionB": "\\(\\dfrac{672}{990}\\)",
//         "qid": "LMA11_01_24_05_13"
//     },
//     {
//         "answer": "",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "24_05",
//         "num": "14",
//         "optionC": "\\(142.5\\) mm",
//         "description": "The length of a pencil is \\(140\\) mm to the nearest millimetre.\nWhat is the upper bound of this measurement?",
//         "topic": "",
//         "optionD": "\\(145\\) mm",
//         "optionA": "\\(140.05\\) mm",
//         "optionB": "\\(140.5\\) mm",
//         "qid": "LMA11_01_24_05_14"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "",
//         "svg": "",
//         "year": "24_05",
//         "num": "15",
//         "optionC": "\\(\\dfrac{1}{3}\\)",
//         "topic": "",
//         "optionD": "\\(3\\)",
//         "description": "Triangle A is enlarged about the centre \\((2, 2)\\) to give triangle B.\n[[graph]]\nWhat is the scale factor of this enlargement?",
//         "optionA": "\\(-3\\)",
//         "optionB": "\\(-\\dfrac{1}{3}\\)",
//         "qid": "LMA11_01_24_05_15"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "23_10",
//         "svg": "",
//         "num": "1",
//         "optionC": "\\(24.3\\)",
//         "optionD": "\\(25.3\\)",
//         "topic": "Statistics",
//         "description": "Calculate the mean of these values:\n\\(26.2\\), \\(22.4\\), \\(37.9\\), \\(28.6\\), \\(22.4\\), \\(14.3\\)",
//         "optionA": "\\(22.4\\)",
//         "optionB": "\\(23.6\\)",
//         "qid": "LMA11_01_23_10_01"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "year": "23_10",
//         "svg": "",
//         "num": "2",
//         "optionC": "Reflex",
//         "description": "What word describes the angle marked \\(x\\)?\n[[svg]]",
//         "topic": "Geometry",
//         "optionD": "Right",
//         "optionA": "Acute",
//         "optionB": "Obtuse",
//         "qid": "LMA11_01_23_10_02"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_10",
//         "num": "3",
//         "optionC": "\\(16k+3\\)",
//         "description": "Simplify \\[8k+4(2k-3)+6\\]",
//         "optionD": "\\(16k-6\\)",
//         "topic": "Algebra",
//         "optionA": "\\(10k+7\\)",
//         "optionB": "\\(10k-6\\)",
//         "qid": "LMA11_01_23_10_03"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "svg": "",
//         "year": "23_10",
//         "num": "4",
//         "optionC": "\\(46\\)",
//         "topic": "Statistics",
//         "optionD": "\\(47\\)",
//         "description": "The table shows the age and test result of some students.\n[[table]]\nHow many of the students passed the test?",
//         "optionA": "\\(16\\)",
//         "optionB": "\\(30\\)",
//         "qid": "LMA11_01_23_10_04"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "23_10",
//         "svg": "",
//         "num": "5",
//         "optionC": "No correlation",
//         "optionD": "Positive correlation",
//         "topic": "Statistics",
//         "description": "Which phrase describes the correlation on this scatter graph?\n[[scatter graph]]",
//         "optionA": "Negative correlation",
//         "optionB": "Descending correlation",
//         "qid": "LMA11_01_23_10_05"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_10",
//         "num": "6",
//         "optionC": "\\(0.0856\\)",
//         "description": "Round \\(0.08567\\) to \\(3\\) decimal places.",
//         "topic": "Number",
//         "optionD": "\\(0.0857\\)",
//         "optionA": "\\(0.085\\)",
//         "optionB": "\\(0.086\\)",
//         "qid": "LMA11_01_23_10_06"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "23_10",
//         "svg": "",
//         "num": "7",
//         "optionC": "\\(\\dfrac{9}{15}\\)",
//         "description": "There are \\(15\\) pencils in a box.\n\\(4\\) of the pencils are blue.\n\\(5\\) of the pencils are red.\nThe rest of the pencils are green.\nOne pencil is taken from the box at random.\nWork out the probability that a green pencil is taken.",
//         "topic": "Probability",
//         "optionD": "\\(\\dfrac{6}{9}\\)",
//         "optionA": "\\(\\dfrac{6}{24}\\)",
//         "optionB": "\\(\\dfrac{6}{15}\\)",
//         "qid": "LMA11_01_23_10_07"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "23_10",
//         "svg": "",
//         "num": "8",
//         "optionC": "\\(32\\dfrac{1}{2}\\%\\)",
//         "optionD": "\\(\\dfrac{12}{37}\\)",
//         "topic": "Number",
//         "description": "Which of these values is the largest?",
//         "optionA": "\\(\\dfrac{21}{60}\\)",
//         "optionB": "\\(0.326\\)",
//         "qid": "LMA11_01_23_10_08"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "svg": "",
//         "year": "23_10",
//         "num": "9",
//         "optionC": "\\(336\\)",
//         "topic": "Number",
//         "optionD": "\\(5376\\)",
//         "description": "What is the highest common factor of \\(48\\) and \\(112\\)?",
//         "optionA": "\\(8\\)",
//         "optionB": "\\(16\\)",
//         "qid": "LMA11_01_23_10_09"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "23_10",
//         "svg": "",
//         "num": "10",
//         "optionC": "\\(16.8\\) cm",
//         "description": "The perimeter of a triangle is \\(84\\) cm.\nThe lengths of the sides of the triangle are in the ratio \\(3:4:5\\).\nWhat is the length of the shortest side of the triangle?",
//         "optionD": "\\(21\\) cm",
//         "topic": "Ratio and Proportion",
//         "optionA": "\\(6\\) cm",
//         "optionB": "\\(7\\) cm",
//         "qid": "LMA11_01_23_10_10"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_10",
//         "num": "11",
//         "optionC": "\\(29\\)",
//         "description": "If \\(a=5\\) and \\(b=-2\\), find the value of \\[(a+b)^{2}-\\sqrt{20a}+ab\\]",
//         "topic": "Algebra",
//         "optionD": "\\(49\\)",
//         "optionA": "\\(-11\\)",
//         "optionB": "\\(9\\)",
//         "qid": "LMA11_01_23_10_11"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "year": "23_10",
//         "svg": "",
//         "num": "12",
//         "optionC": "\\(\\dfrac{1}{3}\\)",
//         "optionD": "\\(3\\)",
//         "topic": "Geometry",
//         "description": "Triangle T is enlarged to produce Triangle S.\nWhat is the scale factor of this enlargement?\n[[graph]]",
//         "optionA": "\\(-3\\)",
//         "optionB": "\\(-\\dfrac{1}{3}\\)",
//         "qid": "LMA11_01_23_10_12"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "23_10",
//         "svg": "",
//         "num": "13",
//         "optionC": "\\(\\dfrac{126}{990}\\)",
//         "topic": "Number",
//         "optionD": "\\(\\dfrac{125}{990}\\)",
//         "description": "How can the recurring decimal \\(0.126262626...\\) be written exactly as a fraction?",
//         "optionA": "\\(\\dfrac{126}{1000}\\)",
//         "optionB": "\\(\\dfrac{126}{999}\\)",
//         "qid": "LMA11_01_23_10_13"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "23_10",
//         "svg": "",
//         "num": "14",
//         "optionC": "\\(w\\le1.5\\)",
//         "description": "Solve \\[4(3-2w)\\le24\\]",
//         "optionD": "\\(w\\ge1.5\\)",
//         "topic": "Inequalities",
//         "optionA": "\\(w\\le-1.5\\)",
//         "optionB": "\\(w\\ge-1.5\\)",
//         "qid": "LMA11_01_23_10_14"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_10",
//         "num": "15",
//         "optionC": "\\(97.75\\times0.85\\)",
//         "description": "A toy shop reduces the price of all its toys by \\(15\\%\\) in a sale.\nA toy in the shop now costs \\(£97.75\\).\nWhich calculation would give the price of the toy before the sale?",
//         "topic": "Percentages",
//         "optionD": "\\(97.75\\times1.15\\)",
//         "optionA": "\\(97.75\\div1.15\\)",
//         "optionB": "\\(97.75\\div0.85\\)",
//         "qid": "LMA11_01_23_10_15"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "23_05",
//         "svg": "",
//         "num": "1",
//         "optionC": "\\(6^{\\circ}\\)C",
//         "optionD": "\\(16^{\\circ}\\)C",
//         "topic": "Number",
//         "description": "In January, the average temperature in Minsk was \\(-5^{\\circ}\\)C.\nIn January, the average temperature in Darwin was \\(33^{\\circ}\\)C warmer than in Minsk.\nIn January, the average temperature in Winnipeg was \\(44^{\\circ}\\)C colder than in Darwin.\nWhat was the average temperature in Winnipeg in January?",
//         "optionA": "\\(-16^{\\circ}\\)C",
//         "optionB": "\\(-6^{\\circ}\\)C",
//         "qid": "LMA11_01_23_05_01"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "23_05",
//         "svg": "",
//         "num": "2",
//         "optionC": "\\(260^{\\circ}\\)",
//         "description": "Which of these is an obtuse angle?",
//         "optionD": "\\(360^{\\circ}\\)",
//         "topic": "Geometry",
//         "optionA": "\\(60^{\\circ}\\)",
//         "optionB": "\\(160^{\\circ}\\)",
//         "qid": "LMA11_01_23_05_02"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "23_05",
//         "svg": "",
//         "num": "3",
//         "optionC": "\\(71\\)",
//         "optionD": "\\(74\\)",
//         "topic": "Statistics",
//         "description": "What is the mode of these numbers?\n\\(83\\), \\(54\\), \\(74\\), \\(39\\), \\(12\\), \\(74\\), \\(56\\), \\(64\\), \\(71\\), \\(74\\)",
//         "optionA": "\\(12\\)",
//         "optionB": "\\(56\\)",
//         "qid": "LMA11_01_23_05_03"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_05",
//         "num": "4",
//         "optionC": "\\(16\\)",
//         "description": "Which of these is not a cube number?",
//         "topic": "Number",
//         "optionD": "\\(64\\)",
//         "optionA": "\\(1\\)",
//         "optionB": "\\(8\\)",
//         "qid": "LMA11_01_23_05_04"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "23_05",
//         "svg": "",
//         "num": "5",
//         "optionC": "\\(1, 4, 9, 16, 25\\)",
//         "description": "Which of these lists contains the first five triangular numbers?",
//         "optionD": "\\(1, 3, 9, 27, 81\\)",
//         "topic": "Number",
//         "optionA": "\\(1, 1, 2, 3, 5\\)",
//         "optionB": "\\(1, 3, 6, 10, 15\\)",
//         "qid": "LMA11_01_23_05_05"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "23_05",
//         "svg": "",
//         "num": "6",
//         "optionC": "\\(18:10\\)",
//         "topic": "Ratio and Proportion",
//         "optionD": "\\(10:18\\)",
//         "description": "A box contains \\(80\\) pens.\n\\(36\\) pens are black, \\(24\\) pens are red and the rest are green.\nWhat is the ratio of green pens to black pens, written in its simplest form?",
//         "optionA": "\\(9:5\\)",
//         "optionB": "\\(5:9\\)",
//         "qid": "LMA11_01_23_05_06"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "svg": "",
//         "year": "23_05",
//         "num": "7",
//         "optionC": "\\((10, 1)\\)",
//         "optionD": "\\((10, -4)\\)",
//         "topic": "Coordinate Geometry",
//         "description": "Find the midpoint of a line with ends at \\((12, -3)\\) and \\((-8, 5)\\).",
//         "optionA": "\\((2, 1)\\)",
//         "optionB": "\\((2, -4)\\)",
//         "qid": "LMA11_01_23_05_07"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_05",
//         "num": "8",
//         "optionC": "\\(125\\text{ cm}^{3}\\)",
//         "description": "What is the volume of a cube with edge \\(5\\) cm?",
//         "topic": "Geometry",
//         "optionD": "\\(150\\text{ cm}^{3}\\)",
//         "optionA": "\\(15\\text{ cm}^{3}\\)",
//         "optionB": "\\(25\\text{ cm}^{3}\\)",
//         "qid": "LMA11_01_23_05_08"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_05",
//         "num": "9",
//         "optionC": "\\(40^{\\circ}\\)",
//         "description": "The table shows the number of animals a vet treats in one week.\n[[table]]\nSaeed draws a pie chart to represent this data.\nWhat size angle should he draw for the sector representing dogs?",
//         "optionD": "\\(80^{\\circ}\\)",
//         "topic": "Statistics",
//         "optionA": "\\(10^{\\circ}\\)",
//         "optionB": "\\(36^{\\circ}\\)",
//         "qid": "LMA11_01_23_05_09"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "23_05",
//         "svg": "",
//         "num": "10",
//         "optionC": "\\(80\\%\\)",
//         "topic": "Percentages",
//         "optionD": "\\(94\\%\\)",
//         "description": "A wooden pole is \\(2\\) metres long.\n\\(120\\) centimetres of the pole is painted blue.\nWhat percentage of the pole is not painted blue?",
//         "optionA": "\\(40\\%\\)",
//         "optionB": "\\(60\\%\\)",
//         "qid": "LMA11_01_23_05_10"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "23_05",
//         "svg": "",
//         "num": "11",
//         "optionC": "\\(y=2-4x\\)",
//         "optionD": "\\(2y=8x-4\\)",
//         "topic": "Graphs",
//         "description": "Find the equation that has a graph which is parallel to the graph of \\[y=4x+2\\]",
//         "optionA": "\\(y=2x+2\\)",
//         "optionB": "\\(y=2x+4\\)",
//         "qid": "LMA11_01_23_05_11"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "23_05",
//         "num": "12",
//         "optionC": "\\(50.3\\) cm",
//         "description": "The radius of a circle is \\(4\\) cm.\nWhat is the circumference of the circle, to \\(1\\) decimal place?",
//         "optionD": "\\(201.1\\) cm",
//         "topic": "Geometry",
//         "optionA": "\\(12.6\\) cm",
//         "optionB": "\\(25.1\\) cm",
//         "qid": "LMA11_01_23_05_12"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "23_05",
//         "svg": "",
//         "num": "13",
//         "optionC": "\\(f=\\dfrac{e+3}{7}\\)",
//         "description": "Make \\(f\\) the subject of the formula \\[e=7(f-3)\\]",
//         "topic": "Algebra",
//         "optionD": "\\(f=\\dfrac{e+21}{7}\\)",
//         "optionA": "\\(f=\\dfrac{e-21}{7}\\)",
//         "optionB": "\\(f=\\dfrac{e-3}{7}\\)",
//         "qid": "LMA11_01_23_05_13"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "23_05",
//         "svg": "",
//         "num": "14",
//         "optionC": "\\(117\\)",
//         "optionD": "\\(133\\)",
//         "topic": "Algebra",
//         "description": "If \\(a=-3\\), \\(b=0.5\\) and \\(c=32\\), find the value of \\[(a-2)^{3}-\\sqrt{4bc}\\]",
//         "optionA": "\\(-133\\)",
//         "optionB": "\\(-117\\)",
//         "qid": "LMA11_01_23_05_14"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "23_05",
//         "svg": "",
//         "num": "15",
//         "optionC": "\\(85\\)",
//         "topic": "Ratio and Proportion",
//         "optionD": "\\(112.5\\)",
//         "description": "\\(y\\) is directly proportional to \\(x\\).\nGiven \\(x=30\\) when \\(y=20\\), find the value of \\(y\\) when \\(x=75\\)",
//         "optionA": "\\(50\\)",
//         "optionB": "\\(65\\)",
//         "qid": "LMA11_01_23_05_15"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "year": "22_10",
//         "svg": "",
//         "num": "1",
//         "optionC": "\\(2p+6q\\)",
//         "description": "Fully simplify \\[6p-3q+4p+9q\\]",
//         "optionD": "\\(10p-12q\\)",
//         "topic": "Algebra",
//         "optionA": "\\(10p+6q\\)",
//         "optionB": "\\(2p-12q\\)",
//         "qid": "LMA11_01_22_10_01"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "22_10",
//         "svg": "",
//         "num": "2",
//         "optionC": "\\(4\\)",
//         "description": "How many lines of symmetry does this shape have?\n[[svg]]",
//         "topic": "Geometry",
//         "optionD": "\\(8\\)",
//         "optionA": "\\(0\\)",
//         "optionB": "\\(2\\)",
//         "qid": "LMA11_01_22_10_02"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "svg": "",
//         "year": "22_10",
//         "num": "3",
//         "optionC": "C and F",
//         "optionD": "D and A",
//         "topic": "Geometry",
//         "description": "Which pair of angles are equal because they are corresponding angles?\n[[svg]]",
//         "optionA": "A and E",
//         "optionB": "B and G",
//         "qid": "LMA11_01_22_10_03"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "svg": "",
//         "year": "22_10",
//         "num": "4",
//         "optionC": "Sector",
//         "topic": "Geometry",
//         "optionD": "Segment",
//         "description": "Which word describes the shaded part of the circle below?\n[[svg]]",
//         "optionA": "Arc",
//         "optionB": "Radius",
//         "qid": "LMA11_01_22_10_04"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "22_10",
//         "svg": "",
//         "num": "5",
//         "optionC": "\\(180\\)",
//         "description": "What is the highest common factor of \\(60\\) and \\(90\\)?",
//         "optionD": "\\(540\\)",
//         "topic": "Number",
//         "optionA": "\\(10\\)",
//         "optionB": "\\(30\\)",
//         "qid": "LMA11_01_22_10_05"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "22_10",
//         "num": "6",
//         "optionC": "\\(0.009\\)",
//         "description": "What is \\(0.008947\\) written to \\(3\\) significant figures?",
//         "topic": "Number",
//         "optionD": "\\(0.00894\\)",
//         "optionA": "\\(0.00895\\)",
//         "optionB": "\\(0.008\\)",
//         "qid": "LMA11_01_22_10_06"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "year": "22_10",
//         "svg": "",
//         "num": "7",
//         "optionC": "\\(255\\)",
//         "description": "The value of \\(A\\) can be calculated using the formula \\[A=4b-c\\]\nWhen \\(A=880\\) and \\(c=140\\), what is the value of \\(b\\)?",
//         "topic": "Algebra",
//         "optionD": "\\(4080\\)",
//         "optionA": "\\(4\\)",
//         "optionB": "\\(185\\)",
//         "qid": "LMA11_01_22_10_07"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "22_10",
//         "svg": "",
//         "num": "8",
//         "optionC": "\\(75\\)",
//         "optionD": "\\(200\\)",
//         "topic": "Ratio and Proportion",
//         "description": "The ratio of adults to children at a hotel is \\(5:3\\).\nThere are \\(120\\) children at the hotel.\nHow many adults are there at the hotel?",
//         "optionA": "\\(45\\)",
//         "optionB": "\\(72\\)",
//         "qid": "LMA11_01_22_10_08"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "22_10",
//         "svg": "",
//         "num": "9",
//         "optionC": "\\(4\\dfrac{5}{12}\\)",
//         "topic": "Number",
//         "optionD": "\\(4\\dfrac{7}{12}\\)",
//         "description": "What is the value of \\[2\\dfrac{3}{4}\\times 1\\dfrac{2}{3}\\]",
//         "optionA": "\\(1\\dfrac{13}{20}\\)",
//         "optionB": "\\(2\\dfrac{1}{2}\\)",
//         "qid": "LMA11_01_22_10_09"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "22_10",
//         "num": "10",
//         "optionC": "\\(1085\\)",
//         "description": "What is the value of \\[4^{3}+25\\times 41-\\sqrt{64}\\div 4\\]",
//         "optionD": "\\(1087\\)",
//         "topic": "Number",
//         "optionA": "\\(910.25\\)",
//         "optionB": "\\(1039\\)",
//         "qid": "LMA11_01_22_10_10"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "svg": "",
//         "year": "22_10",
//         "num": "11",
//         "optionC": "\\(40^{\\circ}\\)C",
//         "optionD": "\\(60^{\\circ}\\)C",
//         "topic": "Statistics",
//         "description": "Use the scatter graph to predict the temperature of a drink that has been made for \\(20\\) minutes.\n[[scatter graph]]",
//         "optionA": "\\(15^{\\circ}\\)C",
//         "optionB": "\\(30^{\\circ}\\)C",
//         "qid": "LMA11_01_22_10_11"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "22_10",
//         "svg": "",
//         "num": "12",
//         "optionC": "\\(\\dfrac{7}{12}\\)",
//         "topic": "Probability",
//         "optionD": "\\(\\dfrac{1}{21}\\)",
//         "description": "A box contains four counters; one is blue, one is green, one is red and one is yellow.\nAnother box contains three counters; one is blue, one is green and one is red.\nA student takes one counter from each box at random.\nWhat is the probability that the student takes two red counters?",
//         "optionA": "\\(\\dfrac{2}{7}\\)",
//         "optionB": "\\(\\dfrac{1}{12}\\)",
//         "qid": "LMA11_01_22_10_12"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "year": "22_10",
//         "svg": "",
//         "num": "13",
//         "optionC": "\\((x-1)(x+6)\\)",
//         "description": "Factorise \\[x^{2}-7x+6\\]",
//         "optionD": "\\((x+1)(x-6)\\)",
//         "topic": "Algebra",
//         "optionA": "\\((x-1)(x-6)\\)",
//         "optionB": "\\((x+1)(x+6)\\)",
//         "qid": "LMA11_01_22_10_13"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "22_10",
//         "num": "14",
//         "optionC": "\\(128\\)",
//         "description": "Find a solution to the equation \\[x^{2}-34=290\\]",
//         "topic": "Algebra",
//         "optionD": "\\(162\\)",
//         "optionA": "\\(16\\)",
//         "optionB": "\\(18\\)",
//         "qid": "LMA11_01_22_10_14"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "svg": "",
//         "year": "22_10",
//         "num": "15",
//         "optionC": "\\(2,3,4,5,6,7\\)",
//         "optionD": "\\(2,3,4,5,6\\)",
//         "topic": "Inequalities",
//         "description": "Which integers satisfy the inequality shown on the number line?\n[[svg]]",
//         "optionA": "\\(3,4,5,6\\)",
//         "optionB": "\\(3,4,5,6,7\\)",
//         "qid": "LMA11_01_22_10_15"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "22_05",
//         "svg": "",
//         "num": "1",
//         "optionC": "Parallelogram",
//         "optionD": "Rhombus",
//         "topic": "Geometry",
//         "description": "Which of these shapes has only one line of symmetry?",
//         "optionA": "Equilateral triangle",
//         "optionB": "Kite",
//         "qid": "LMA11_01_22_05_01"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "year": "22_05",
//         "svg": "",
//         "num": "2",
//         "optionC": "\\(2\\), \\(2\\)",
//         "description": "Which of the lists below includes all the common factors of \\(16\\) and \\(20\\)?",
//         "topic": "Number",
//         "optionD": "\\(80\\), \\(160\\), \\(240\\)",
//         "optionA": "\\(1\\), \\(2\\), \\(4\\)",
//         "optionB": "\\(1\\), \\(2\\), \\(4\\), \\(5\\), \\(8\\)",
//         "qid": "LMA11_01_22_05_02"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "22_05",
//         "num": "3",
//         "optionC": "\\(46b+52\\)",
//         "description": "Simplify fully \\[9(2b+8)+4(7b-5)\\]",
//         "optionD": "\\(46b+92\\)",
//         "topic": "Algebra",
//         "optionA": "\\(46b+3\\)",
//         "optionB": "\\(46b+13\\)",
//         "qid": "LMA11_01_22_05_03"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "22_05",
//         "svg": "",
//         "num": "4",
//         "optionC": "\\(c\\) and \\(h\\)",
//         "topic": "Geometry",
//         "optionD": "\\(d\\) and \\(f\\)",
//         "description": "Which of these is a pair of corresponding angles?\n[[svg]]",
//         "optionA": "\\(a\\) and \\(e\\)",
//         "optionB": "\\(b\\) and \\(d\\)",
//         "qid": "LMA11_01_22_05_04"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "svg": "",
//         "year": "22_05",
//         "num": "5",
//         "optionC": "Radius",
//         "optionD": "Segment",
//         "topic": "Geometry",
//         "description": "What name is given to a straight line that connects \\(2\\) points on the circumference of a circle but does NOT pass through the centre of the circle?",
//         "optionA": "Chord",
//         "optionB": "Diameter",
//         "qid": "LMA11_01_22_05_05"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "22_05",
//         "svg": "",
//         "num": "6",
//         "optionC": "\\(0.0793\\)",
//         "description": "What is \\(0.07936\\) written to \\(3\\) significant figures?",
//         "topic": "Number",
//         "optionD": "\\(0.0794\\)",
//         "optionA": "\\(0.08\\)",
//         "optionB": "\\(0.079\\)",
//         "qid": "LMA11_01_22_05_06"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "22_05",
//         "svg": "",
//         "num": "7",
//         "optionC": "\\(75\\)",
//         "description": "The ratio of men to women who work at a college is \\(3:5\\).\nThere are \\(120\\) women who work at the college.\nHow many men work at the college?",
//         "optionD": "\\(200\\)",
//         "topic": "Ratio and Proportion",
//         "optionA": "\\(45\\)",
//         "optionB": "\\(72\\)",
//         "qid": "LMA11_01_22_05_07"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "22_05",
//         "svg": "",
//         "num": "8",
//         "optionC": "\\(\\dfrac{23}{12}\\)",
//         "topic": "Number",
//         "optionD": "\\(\\dfrac{31}{12}\\)",
//         "description": "Work out the value of \\[1\\dfrac{1}{6}-\\dfrac{3}{4}\\]",
//         "optionA": "\\(\\dfrac{5}{12}\\)",
//         "optionB": "\\(\\dfrac{13}{12}\\)",
//         "qid": "LMA11_01_22_05_08"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "22_05",
//         "svg": "",
//         "num": "9",
//         "optionC": "\\(60\\)",
//         "optionD": "\\(382\\)",
//         "topic": "Number",
//         "description": "Work out the value of \\[100+(\\sqrt{121}\\times4-13)-7^{2}\\]",
//         "optionA": "\\(82\\)",
//         "optionB": "\\(-48\\)",
//         "qid": "LMA11_01_22_05_09"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "22_05",
//         "svg": "",
//         "num": "10",
//         "optionC": "\\(\\dfrac{2}{14}\\)",
//         "description": "A teacher chooses \\(1\\) letter from the word SCIENCE and \\(1\\) letter from the word HISTORY.\nWhat is the probability that he chooses the letter I from both words?",
//         "topic": "Probability",
//         "optionD": "\\(\\dfrac{1}{49}\\)",
//         "optionA": "\\(\\dfrac{2}{7}\\)",
//         "optionB": "\\(\\dfrac{1}{91}\\)",
//         "qid": "LMA11_01_22_05_10"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "22_05",
//         "svg": "",
//         "num": "11",
//         "optionC": "\\(60\\)",
//         "description": "The absence and average test score of each student in a class are shown in a scatter graph.\nA student with \\(25\\%\\) absence joins the class.\nWhat would be the best estimate of his average test score?\n[[scatter graph]]",
//         "optionD": "\\(70\\)",
//         "topic": "Statistics",
//         "optionA": "\\(40\\)",
//         "optionB": "\\(50\\)",
//         "qid": "LMA11_01_22_05_11"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "22_05",
//         "svg": "",
//         "num": "12",
//         "optionC": "\\(105\\)",
//         "topic": "Algebra",
//         "optionD": "\\(156\\)",
//         "description": "A telephone company uses this formula to calculate how much a customer must pay \\[T=0.25p+0.2n+15\\] where\n\\(T\\) is the total cost (in $)\n\\(p\\) is the number of minutes on calls during peak times\n\\(n\\) is the number of minutes on calls during non-peak times\nA customer spends \\(60\\) minutes on calls during non-peak times.\nThe total cost that she must pay is \\(\\$51\\).\nHow many minutes did she spend on calls during peak times?",
//         "optionA": "\\(42\\)",
//         "optionB": "\\(96\\)",
//         "qid": "LMA11_01_22_05_12"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "svg": "",
//         "year": "22_05",
//         "num": "13",
//         "optionC": "\\((x-4)(x-6)\\)",
//         "optionD": "\\((x-4)(x+6)\\)",
//         "topic": "Algebra",
//         "description": "Factorise \\[x^{2}-10x+24\\]",
//         "optionA": "\\((x-2)(x+12)\\)",
//         "optionB": "\\((x+2)(x-12)\\)",
//         "qid": "LMA11_01_22_05_13"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "year": "22_05",
//         "svg": "",
//         "num": "14",
//         "optionC": "\\(-1\\le x<4\\)",
//         "description": "Which inequality is illustrated on the number line below?\n[[svg]]",
//         "topic": "Algebra",
//         "optionD": "\\(-1\\le x\\le4\\)",
//         "optionA": "\\(-1<x<4\\)",
//         "optionB": "\\(-1<x\\le4\\)",
//         "qid": "LMA11_01_22_05_14"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "22_05",
//         "num": "15",
//         "optionC": "\\(x=98\\)",
//         "description": "Find a solution to the equation \\[x^{2}+30=226\\]",
//         "optionD": "\\(x=128\\)",
//         "topic": "Algebra",
//         "optionA": "\\(x=14\\)",
//         "optionB": "\\(x=16\\)",
//         "qid": "LMA11_01_22_05_15"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "21_10",
//         "svg": "",
//         "num": "1",
//         "optionC": "\\(17b-8c\\)",
//         "topic": "Algebra",
//         "optionD": "\\(17b-2c\\)",
//         "description": "Simplify \\[11b-5c-6b+3c\\]",
//         "optionA": "\\(5b-8c\\)",
//         "optionB": "\\(5b-2c\\)",
//         "qid": "LMA11_01_21_10_01"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "year": "21_10",
//         "svg": "",
//         "num": "2",
//         "optionC": "Reflex",
//         "optionD": "Right",
//         "topic": "Geometry",
//         "description": "Which word is used to describe a \\(195^{\\circ}\\) angle?",
//         "optionA": "Acute",
//         "optionB": "Obtuse",
//         "qid": "LMA11_01_21_10_02"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "21_10",
//         "num": "3",
//         "optionC": "\\(\\dfrac{2}{11}\\)",
//         "description": "One letter is chosen at random from the word M A T H E M A T I C S\nWhat is the probability that the letter chosen is a T?",
//         "optionD": "\\(\\dfrac{9}{11}\\)",
//         "topic": "Probability",
//         "optionA": "\\(\\dfrac{1}{8}\\)",
//         "optionB": "\\(\\dfrac{2}{9}\\)",
//         "qid": "LMA11_01_21_10_03"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "year": "21_10",
//         "svg": "",
//         "num": "4",
//         "optionC": "C",
//         "topic": "Geometry",
//         "optionD": "D",
//         "description": "On which of these diagrams is a segment illustrated?\n[[svg]]",
//         "optionA": "A",
//         "optionB": "B",
//         "qid": "LMA11_01_21_10_04"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "svg": "",
//         "year": "21_10",
//         "num": "5",
//         "optionC": "Negative correlation",
//         "optionD": "No correlation",
//         "topic": "Statistics",
//         "description": "Which phrase describes the relationship illustrated on the scatter graph below?\n[[scatter diagram]]",
//         "optionA": "Direct correlation",
//         "optionB": "Positive correlation",
//         "qid": "LMA11_01_21_10_05"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "year": "21_10",
//         "svg": "",
//         "num": "6",
//         "optionC": "\\(9\\)",
//         "description": "There are 30 students in a class.\r\nEach student plays a game against their teacher which they either win, draw or lose.\r\nEach student then takes a test that they can pass or fail.\r\nSome information about the students is recorded in the two-way table below.\n[[table]]\nHow many students draw the game and fail the test?",
//         "topic": "Statistics",
//         "optionD": "\\(16\\)",
//         "optionA": "\\(2\\)",
//         "optionB": "\\(7\\)",
//         "qid": "LMA11_01_21_10_06"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "year": "21_10",
//         "svg": "",
//         "num": "7",
//         "optionC": "\\(8.28\\)",
//         "description": "Round \\(8.279\\) to \\(2\\) decimal places.",
//         "topic": "Number",
//         "optionD": "\\(8.3\\)",
//         "optionA": "\\(8.2\\)",
//         "optionB": "\\(8.27\\)",
//         "qid": "LMA11_01_21_10_07"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "21_10",
//         "svg": "",
//         "num": "8",
//         "optionC": "\\(85\\)",
//         "optionD": "\\(100\\)",
//         "topic": "Statistics",
//         "description": "A group of students each took a test in Maths and then a test in Computing.\nTheir scores from each of the tests are displayed on the scatter graph below.\n[[scatter graph]]\nAnother student took the Maths test and scored \\(70\\) marks.\nWhat mark would this student be predicted to get on the Computing test?",
//         "optionA": "\\(50\\)",
//         "optionB": "\\(80\\)",
//         "qid": "LMA11_01_21_10_08"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "svg": "",
//         "year": "21_10",
//         "num": "9",
//         "optionC": "\\(8^{9}\\)",
//         "topic": "Algebra",
//         "optionD": "\\(8^{18}\\)",
//         "description": "Write the following expression as a single power of \\(8\\) \\[(8^{6})^{3}\\]",
//         "optionA": "\\(8^{2}\\)",
//         "optionB": "\\(8^{3}\\)",
//         "qid": "LMA11_01_21_10_09"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "21_10",
//         "num": "10",
//         "optionC": "\\(378\\)",
//         "description": "If \\(a=3\\), \\(b=1\\) and \\(c=5\\), find the value of \\[(4a+3b)^{2}+ac^{2}\\]",
//         "optionD": "\\(450\\)",
//         "topic": "Algebra",
//         "optionA": "\\(228\\)",
//         "optionB": "\\(300\\)",
//         "qid": "LMA11_01_21_10_10"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "21_10",
//         "svg": "",
//         "num": "11",
//         "optionC": "\\(30\\)",
//         "description": "Work out \\[32+16\\div(8-4)\\]",
//         "topic": "Number",
//         "optionD": "\\(36\\)",
//         "optionA": "\\(2\\)",
//         "optionB": "\\(12\\)",
//         "qid": "LMA11_01_21_10_11"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "21_10",
//         "svg": "",
//         "num": "12",
//         "optionC": "\\((1,3)\\)",
//         "optionD": "\\((3,0)\\)",
//         "topic": "Geometry",
//         "description": "Shape ABCD is a parallelogram.\n[[graph]]\nWhat could the coordinates of Point D be?",
//         "optionA": "\\((-2,-1)\\)",
//         "optionB": "\\((-1,4)\\)",
//         "qid": "LMA11_01_21_10_12"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "21_10",
//         "svg": "",
//         "num": "13",
//         "optionC": "\\(\\dfrac{246246246}{999999999}\\)",
//         "topic": "Number",
//         "optionD": "\\(\\dfrac{246246246}{1000000000}\\)",
//         "description": "Which fraction is equivalent to the recurring decimal \\(0.246246246...\\)?",
//         "optionA": "\\(\\dfrac{246}{999}\\)",
//         "optionB": "\\(\\dfrac{246}{1000}\\)",
//         "qid": "LMA11_01_21_10_13"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "21_10",
//         "num": "14",
//         "optionC": "\\(\\dfrac{1}{2}\\)",
//         "description": "Triangle A is enlarged to produce Triangle B.\n[[graph]]\nWhat scale factor has Triangle A been enlarged by?",
//         "optionD": "\\(2\\)",
//         "topic": "Geometry",
//         "optionA": "\\(-\\dfrac{1}{2}\\)",
//         "optionB": "\\(-2\\)",
//         "qid": "LMA11_01_21_10_14"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "21_10",
//         "num": "15",
//         "optionC": "\\(8.995\\) km",
//         "description": "The distance that an athlete runs is given as \\(9\\) km to the nearest metre.\nWhat is the minimum distance that the athlete must have run?",
//         "topic": "Number",
//         "optionD": "\\(8.9995\\) km",
//         "optionA": "\\(8.5\\) km",
//         "optionB": "\\(8.95\\) km",
//         "qid": "LMA11_01_21_10_15"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "21_05",
//         "svg": "",
//         "num": "1",
//         "optionC": "\\(25f-12y\\)",
//         "optionD": "\\(25f-2y\\)",
//         "topic": "Algebra",
//         "description": "Simplify \\[14f-7y+11f+5y\\]",
//         "optionA": "\\(3f-12y\\)",
//         "optionB": "\\(3f-2y\\)",
//         "qid": "LMA11_01_21_05_01"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "21_05",
//         "svg": "",
//         "num": "2",
//         "optionC": "Acute",
//         "optionD": "Obtuse",
//         "topic": "Geometry",
//         "description": "Which word describes the angle marked \\(x\\) on the diagram below?\n[[svg]]",
//         "optionA": "Reflex",
//         "optionB": "Right",
//         "qid": "LMA11_01_21_05_02"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "21_05",
//         "svg": "",
//         "num": "3",
//         "optionC": "\\(5.52\\)",
//         "description": "Find the mean of \\(3.41\\), \\(4.56\\), \\(4.56\\), \\(5.26\\), \\(6.35\\), \\(7.11\\), \\(8.93\\)",
//         "topic": "Statistics",
//         "optionD": "\\(5.74\\)",
//         "optionA": "\\(4.56\\)",
//         "optionB": "\\(5.26\\)",
//         "qid": "LMA11_01_21_05_03"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "21_05",
//         "num": "4",
//         "optionC": "Negative",
//         "description": "Which word describes the correlation shown on the scatter graph below?\n[[scatter graph]]",
//         "optionD": "Positive",
//         "topic": "Statistics",
//         "optionA": "Direct",
//         "optionB": "Downward",
//         "qid": "LMA11_01_21_05_04"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "21_05",
//         "svg": "",
//         "num": "5",
//         "optionC": "\\(15\\)",
//         "topic": "Statistics",
//         "optionD": "\\(20\\)",
//         "description": "Students in a class are asked their age and how many siblings they have.\nTheh results are recorded in the table below.\n[[table]]\nHow many 13-year-old students have more than one sibling?",
//         "optionA": "\\(8\\)",
//         "optionB": "\\(12\\)",
//         "qid": "LMA11_01_21_05_05"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "svg": "",
//         "year": "21_05",
//         "num": "6",
//         "optionC": "\\(1.357\\)",
//         "optionD": "\\(1.358\\)",
//         "topic": "Number",
//         "description": "What is \\(1.3579\\) to \\(3\\) decimal places?",
//         "optionA": "\\(1.35\\)",
//         "optionB": "\\(1.36\\)",
//         "qid": "LMA11_01_21_05_06"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "year": "21_05",
//         "svg": "",
//         "num": "7",
//         "optionC": "\\(\\$64\\)",
//         "description": "Chhaya, Kinjal and Sajni share \\(\\$240\\) in the ratio \\(8:4:3\\)\nHow much will Kinjal get?",
//         "topic": "Ratio and Proportion",
//         "optionD": "\\(\\$128\\)",
//         "optionA": "\\(\\$48\\)",
//         "optionB": "\\(\\$60\\)",
//         "qid": "LMA11_01_21_05_07"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "21_05",
//         "svg": "",
//         "num": "8",
//         "optionC": "\\(90\\)",
//         "description": "What is the highest common factor of \\(18\\) and \\(30\\)?",
//         "optionD": "\\(540\\)",
//         "topic": "Number",
//         "optionA": "\\(3\\)",
//         "optionB": "\\(6\\)",
//         "qid": "LMA11_01_21_05_08"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "D",
//         "year": "21_05",
//         "svg": "",
//         "num": "9",
//         "optionC": "\\(57\\%\\)",
//         "topic": "Number",
//         "optionD": "\\(\\dfrac{6}{11}\\)",
//         "description": "Which of these values is the lowest?",
//         "optionA": "\\(0.567\\)",
//         "optionB": "\\(\\dfrac{5}{9}\\)",
//         "qid": "LMA11_01_21_05_09"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "svg": "",
//         "year": "21_05",
//         "num": "10",
//         "optionC": "\\(\\dfrac{7}{18}\\)",
//         "optionD": "\\(\\dfrac{11}{18}\\)",
//         "topic": "Probability",
//         "description": "A box contains only \\(5\\) red beads, \\(6\\) yellow beads and \\(7\\) green beads.\nOne bead is taken from the box at random.\nWhat is the probability that the bead taken is green?",
//         "optionA": "\\(\\dfrac{1}{3}\\)",
//         "optionB": "\\(\\dfrac{7}{11}\\)",
//         "qid": "LMA11_01_21_05_10"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "21_05",
//         "num": "11",
//         "optionC": "\\(2\\)",
//         "description": "Find the scale factor that shape A should be enlarged by to get shape B.\n[[svg]]",
//         "topic": "Geometry",
//         "optionD": "\\(3\\)",
//         "optionA": "\\(\\dfrac{2}{3}\\)",
//         "optionB": "\\(1.5\\)",
//         "qid": "LMA11_01_21_05_11"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "21_05",
//         "num": "12",
//         "optionC": "\\(71\\)",
//         "description": "If \\(a=-10\\), \\(b=-4\\) and \\(c=3\\), find the value of \\[a+(3b+c)^{2}\\]",
//         "optionD": "\\(215\\)",
//         "topic": "Algebra",
//         "optionA": "\\(-91\\)",
//         "optionB": "\\(-13\\)",
//         "qid": "LMA11_01_21_05_12"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "21_05",
//         "svg": "",
//         "num": "13",
//         "optionC": "\\(\\$1089\\)",
//         "optionD": "\\(\\$1100\\)",
//         "topic": "Number",
//         "description": "The price of a holiday has increased by \\(10\\%\\).\nThe holiday now costs \\(\\$990\\).\nHow much would the holiday have cost before the price increase?",
//         "optionA": "\\(\\$891\\)",
//         "optionB": "\\(\\$900\\)",
//         "qid": "LMA11_01_21_05_13"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "21_05",
//         "svg": "",
//         "num": "14",
//         "optionC": "\\(\\dfrac{37373737}{99999999}\\)",
//         "topic": "Number",
//         "optionD": "\\(\\dfrac{37373737}{100000000}\\)",
//         "description": "How can the recurring decimal below be written as a fraction? \\[0.37373737...\\]",
//         "optionA": "\\(\\dfrac{37}{99}\\)",
//         "optionB": "\\(\\dfrac{37}{100}\\)",
//         "qid": "LMA11_01_21_05_14"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "21_05",
//         "svg": "",
//         "num": "15",
//         "optionC": "\\(x<2\\)",
//         "description": "Solve the inequality \\(5(12-3x)<30\\)",
//         "optionD": "\\(x>2\\)",
//         "topic": "Algebra",
//         "optionA": "\\(x<-2\\)",
//         "optionB": "\\(x>-2\\)",
//         "qid": "LMA11_01_21_05_15"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "20_05",
//         "svg": "",
//         "num": "1",
//         "optionC": "\\(-12^{\\circ}\\)C",
//         "description": "The temperature at midday in Moscow is \\(-11^{\\circ}\\)C.\nBy \\(4\\) pm, the temperature decreases by \\(4^{\\circ}\\)C.\nBy \\(8\\) pm, the temperature decreases by another \\(3^{\\circ}\\)C.\nWhat is the temperature in Moscow at \\(8\\) pm?",
//         "topic": "Number",
//         "optionD": "\\(-18^{\\circ}\\)C",
//         "optionA": "\\(-4^{\\circ}\\)C",
//         "optionB": "\\(-10^{\\circ}\\)C",
//         "qid": "LMA11_01_20_05_01"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "year": "20_05",
//         "svg": "",
//         "num": "2",
//         "optionC": "\\(3:2\\)",
//         "optionD": "\\(3:5\\)",
//         "topic": "Ratio and Proportion",
//         "description": "There are \\(30\\) students in a class.\n\\(12\\) of the students are boys.\nThe rest of the class are girls.\nWhat is the ratio of girls to boys in the simplest form?",
//         "optionA": "\\(2:3\\)",
//         "optionB": "\\(2:5\\)",
//         "qid": "LMA11_01_20_05_02"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "20_05",
//         "svg": "",
//         "num": "3",
//         "optionC": "\\(3\\)",
//         "topic": "Statistics",
//         "optionD": "\\(7\\)",
//         "description": "\\(20\\) children are asked how many pieces of homework they got that day.\nThe results are shown in the bar chart below.\n[[bar chart]]\nWhat is the modal number of pieces of homework per child?",
//         "optionA": "\\(1\\)",
//         "optionB": "\\(2.5\\)",
//         "qid": "LMA11_01_20_05_03"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "20_05",
//         "num": "4",
//         "optionC": "Obtuse",
//         "description": "Which word describes the angle marked \\(x\\)?\n[[svg]]",
//         "optionD": "Reflex",
//         "topic": "Geometry",
//         "optionA": "Acute",
//         "optionB": "Right",
//         "qid": "LMA11_01_20_05_04"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "20_05",
//         "svg": "",
//         "num": "5",
//         "optionC": "\\(1, 4, 9, 16, 25\\)",
//         "description": "What are the first five triangular numbers?",
//         "topic": "Number",
//         "optionD": "\\(1, 8, 27, 64, 125\\)",
//         "optionA": "\\(1, 1, 2, 3, 5\\)",
//         "optionB": "\\(1, 3, 6, 10, 15\\)",
//         "qid": "LMA11_01_20_05_05"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "20_05",
//         "svg": "",
//         "num": "6",
//         "optionC": "\\(16\\)",
//         "optionD": "\\(64\\)",
//         "topic": "Number",
//         "description": "Which of these is a cube number but not a square number?",
//         "optionA": "\\(1\\)",
//         "optionB": "\\(8\\)",
//         "qid": "LMA11_01_20_05_06"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "20_05",
//         "svg": "",
//         "num": "7",
//         "optionC": "\\(20\\%\\)",
//         "topic": "Number",
//         "optionD": "\\(50\\%\\)",
//         "description": "A teacher ran a \\(4\\) km race.\n\\(80\\) m of the race was on grass.\nThe rest of the race was on the road.\nWhat percentage of the race was on grass?",
//         "optionA": "\\(2\\%\\)",
//         "optionB": "\\(5\\%\\)",
//         "qid": "LMA11_01_20_05_07"
//     },
//     {
//         "answer": "B",
//         "paper": "LMA11_01",
//         "year": "20_05",
//         "svg": "",
//         "num": "8",
//         "optionC": "\\(201\\) cm",
//         "description": "The radius of a circle is \\(8\\) cm.\nWhat is the circumference of the circle to the nearest centimetre?",
//         "optionD": "\\(804\\) cm",
//         "topic": "Geometry",
//         "optionA": "\\(25\\) cm",
//         "optionB": "\\(50\\) cm",
//         "qid": "LMA11_01_20_05_08"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "20_05",
//         "num": "9",
//         "optionC": "\\(y=6x+4\\)",
//         "description": "Which of these lines is parallel to \\(y=3x+2\\)?",
//         "topic": "Algebra",
//         "optionD": "\\(y=3x+4\\)",
//         "optionA": "\\(2y=3x+2\\)",
//         "optionB": "\\(y=4x+2\\)",
//         "qid": "LMA11_01_20_05_09"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "A",
//         "year": "20_05",
//         "svg": "",
//         "num": "10",
//         "optionC": "\\((4, 3)\\)",
//         "optionD": "\\((4, 6)\\)",
//         "topic": "Geometry",
//         "description": "P and Q are two points on a coordinate grid.\nP has coordinates \\((-2, 9)\\).\nQ has coordinates \\((6, -3)\\).\nWhat are the coordinates of the midpoint of PQ?",
//         "optionA": "\\((2, 3)\\)",
//         "optionB": "\\((2, 6)\\)",
//         "qid": "LMA11_01_20_05_10"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "B",
//         "year": "20_05",
//         "svg": "",
//         "num": "11",
//         "optionC": "\\(180\\)",
//         "topic": "Statistics",
//         "optionD": "\\(324\\)",
//         "description": "There are \\(450\\) students in a school.\nEach of the students speaks one foreign language.\nThe foreign language that each student speaks is displayed in a pie chart below.\n[[pie chart]]\nHow many students in the school speak German?",
//         "optionA": "\\(72\\)",
//         "optionB": "\\(90\\)",
//         "qid": "LMA11_01_20_05_11"
//     },
//     {
//         "answer": "C",
//         "paper": "LMA11_01",
//         "svg": "",
//         "year": "20_05",
//         "num": "12",
//         "optionC": "\\(160\\text{ cm}^{3}\\)",
//         "description": "What is the volume of a cuboid?\n[[svg]]",
//         "optionD": "\\(184\\text{ cm}^{3}\\)",
//         "topic": "Geometry",
//         "optionA": "\\(17\\text{ cm}^{3}\\)",
//         "optionB": "\\(92\\text{ cm}^{3}\\)",
//         "qid": "LMA11_01_20_05_12"
//     },
//     {
//         "answer": "D",
//         "paper": "LMA11_01",
//         "year": "20_05",
//         "svg": "",
//         "num": "13",
//         "optionC": "\\(n=\\dfrac{3m^{2}}{7}\\)",
//         "description": "Make \\(n\\) the subject of the formula \\[m=\\dfrac{\\sqrt{7n}}{3}\\]",
//         "topic": "Algebra",
//         "optionD": "\\(n=\\dfrac{(3m)^{2}}{7}\\)",
//         "optionA": "\\(n=3\\left(\\dfrac{m}{7}\\right)^{2}\\)",
//         "optionB": "\\(n=\\left(\\dfrac{3m}{7}\\right)^{2}\\)",
//         "qid": "LMA11_01_20_05_13"
//     },
//     {
//         "paper": "LMA11_01",
//         "answer": "C",
//         "svg": "",
//         "year": "20_05",
//         "num": "14",
//         "optionC": "\\(46\\)",
//         "optionD": "\\(58\\)",
//         "topic": "Algebra",
//         "description": "Find the value of \\[\\dfrac{5p+\\sqrt{4q}}{(6r+5)^{2}}\\] when \\(p=8\\), \\(q=9\\) and \\(r=-1\\)",
//         "optionA": "\\(-58\\)",
//         "optionB": "\\(-46\\)",
//         "qid": "LMA11_01_20_05_14"
//     },
//     {
//         "answer": "A",
//         "paper": "LMA11_01",
//         "year": "20_05",
//         "svg": "",
//         "num": "15",
//         "optionC": "\\(x=3y\\)",
//         "description": "\\(y\\) is directly proportional to \\(x\\).\n\\(y=48\\) when \\(x=16\\).\nFind an expression for \\(y\\) in terms of \\(x\\).",
//         "optionD": "\\(x=y-32\\)",
//         "topic": "Algebra",
//         "optionA": "\\(y=3x\\)",
//         "optionB": "\\(y=2x+16\\)",
//         "qid": "LMA11_01_20_05_15"
//     }
// ]